### ISSUE TITLE
Not running on macOS Monterey 12.4 

### ISSUE THREAD

**Issue by Bubobubobubobubo** [polymorphicengine/tidal-gui#20]
I thought that you would like some feedback on the 1.9 build 😄 .
Running on macOS Monterey 12.4, Intel MBPro:

``` 
Uncaught Exception:
Error: Timeout
at Timeout._onTimeout (/private/var/folders/zq/nwpwzg_s2rq87xq7zggqfvhw0000gn/T/AppTranslocation/B3C3BB38-83E6-4B41-807F-A491A27D2FEF/d/TidalCyclesInterface.app/Contents/Resources/app/node_modules/wait-on/lib/wait-on.js:113:10)
at listOnTimeout (internal/timers.js:531:17)
at processTimers (internal/timers.js:475:7)
```

**Comment by polymorphicengine** [comment]
Ah thanks a lot, that's actually very helpful
could you also try the previous build?

right now I'm unsure if it's an error from 1.9 or an error that was already there and i didn't catch for some reason

**Comment by Bubobubobubobubo** [comment]
Sorry for not answering sooner! The previous release runs fine. I'm able to write and evaluate patterns but I can't hear any sound at all. Is it bundling its own SC and SuperDirt?

**Comment by polymorphicengine** [comment]
ok, good to know!

no, you have to start SuperDirt yourself, just like in the other editor plugins.. could it be that your mac is supressing the OSC messages?
